### ISSUE TITLE
Fix re-entrant lock issues BFT has with the AFT class

### ISSUE THREAD

**Issue by ashamis** [microsoft/CCF#1601]
When replicas execute on the backup they sometimes run into the issue that they need to take locks that the same thread has already acquired. This caused a deadlock! The current solution is to skip locking but this is a short term hack and a real solution needs to be put in.

Functions with this issue:
- [ ] aft::get_commit_idx (#2065)
- [ ] aft::get_term (#2065)
- [x] get_commit_term_and_idx (#2062)
- [x] aft::get_term(idx) (#2062)
- [x] aft::replicate (#1887)
- [x] aft::periodic (#1887)
