### ISSUE TITLE
AFT: View changes

### ISSUE THREAD

**Issue by ashamis** [microsoft/CCF#1709]
Get AFT view-changes to work

Trigger view-change
- [x] Detect if the primary is not issuing transactions in a timely manner (#1770)
- [x] Detect if the primary is not creating signatures or adding evidence to the ledger in a timely manner (#1813)

Execute view-change
- [x] Every replica needs to create and send a "view-change" message (#1835)
- [x] When the new proposed primary collects enough evidence it needs to send a "new-view" message (#1861)
- [x] Before applying a view-change the replica needs to validate the view-change message on the backups (#1861, #1864)
- [ ] When a replica receives an append entry it needs to validate that is comes from a valid primary  (#1864, #1881)

**Comment by ashamis** [comment]
For the bullet point "Before applying a view-change the replica needs to validate the view-change message on the backups". The replicas needs to make sure the new-view tx has:
- The that the replica received the correct number of signatures.
- Ensure that the progress tracker agrees for which seqno it is applying the new-view tx for.

**Comment by ashamis** [comment]
for the bullet point " When a replica receives an append entry it needs to validate that is comes from a valid primary". There are some checks we need to do.
- Check if the replica that is sending said data can be the primary for that view i.e. we determine the primary deterministically based on the view
- Then check if we have the required evidence for said view
