### ISSUE TITLE
Setup Azure Container Registry pipeline for docker images 

### ISSUE THREAD

**Issue by jumaffre** [microsoft/CCF#3798]
We should setup a private Azure Container Registry (ACR) for CCF docker images so that our CI and customers are not affected by the upcoming docker.io throttling limits.

This should include a CI pipeline to automatically push these images to ACR there (rather than docker.io) as well as the public Microsoft Container Registry (MCR). 

Tasks:
- [x] 1. Setup CI pipeline to automatically publish CI images to ACR (#3806).
- [x] 2. Setup CI pipeline to automatically publish app images to ACR (#3821).
- [x] 3. Setup MCR for app images
- [x] 4. Rename images to include `sgx` in image name, more specifically as a tag (#3839).
- [ ] 5. Automatically include docker image names in release notes.
