### ISSUE TITLE
Release and packaging for SEV-SNP 

### ISSUE THREAD

**Issue by jumaffre** [microsoft/CCF#4069]
- [x] Change `COMPILE_TARGETS` to support one target at a time #4367 
- [x] Add `snp` as an option to `COMPILE_TARGET` #4367 
- [x] Refactor attestation code to use compile time option instead of runtime.
- [ ] Decorate binaries with `.snp` for `snp` `COMPILE_TARGET` #4569
- [x] Separate containers to be per target (sgx, snp, insecure virtual) #4381 
  - a. Create SNP and virtual versions of `ccf/app/dev`, `ccf/app/run` and `ccf/app/run-js` containers #4381
  - b. Create SNP and virtual versions of `ccf/ci/` containers https://github.com/microsoft/CCF/pull/4461
- [x] Separate .deb files to be per target #4367 
- [x] Include platform type in project name

**Comment by DomAyre** [comment]
Another way we could achieve point 1. 

We have two compile time values:
- `COMPILE_TARGETS` what we have today, defines what code is compiled.
- A value to set a default for the `TEST_ENCLAVE` runtime configuration option (perhaps with a new name) which defines what target we expect to run the node on.

**Comment by DomAyre** [comment]
It's also worth noting we should probably update the sample constitutions to allow operators to manage the tables used in SNP attestation

**Comment by achamayou** [comment]
@DomAyre I think we've done most of that, except perhaps the binary decoration? I think we want to close this before 3.0 final, and so this effectively should become p0.
