### ISSUE TITLE
`3.0.0-rc0` follow-up TODOs

### ISSUE THREAD

**Issue by jumaffre** [microsoft/CCF#4419]
Follow-up from the recent `3.0.0-rc0` release, the following points should be addressed to get the CI/release pipeline in a good state:
- [x] Revert main SGX pool to CoffeeLake https://github.com/microsoft/CCF/pull/4408 
- [x] Fix containers release job https://github.com/microsoft/CCF/pull/4417
- [x] Re-enable tests on SNPCC for release job https://github.com/microsoft/CCF/pull/4422
- [x] Fix LTS compatibility test (not until `release/3.x` branch is created)
- [x] Include platform (sgx, snp, virtual) in the cmake project name https://github.com/microsoft/CCF/pull/4421
- [x] Fix and re-enable COSE test in full test suite 
- [x] Fix `vegeta` stress test on SNPCC
- [x] Re-enable all pipelines (Daily, stress, etc.)
- [x] Re-enable/re-create disabled/flaky SNPCC executors
- [x] Aggregate release notes before `rc1` #4424 
- [x] Remove extra `.host` library in SGX package #4428 
- [x] Update docs and samples #4467 
- [x] Re-add open-enclave to non-SGX docker images #4431
