### ISSUE TITLE
Catastophic recovery using key shares

### ISSUE THREAD

**Issue by achamayou** [microsoft/CCF#51]
Use https://github.com/dsprenkels/sss adapted to run in an enclave to implement Shamir's Secret Sharing.

- [x] 1. Link sss to CCF enclave (#810)
- [x] 2. Add `ksk_m` to `ccf.members` table and generate in test infra/docs.
- [x] 3. Generate `k_z` on start-up, split it into "some" shares, encrypt the shares and keep encrypted shares in node's memory for now.
- [x] 4. Add new `ccf.shares` table and populate it with `(ledger secrets)k_z` and `[(shares_m)ksk_m]` on start-up.
- [x] 5. Serve members' shares on `getEncryptedRecoveryShare` RPC and allow members to easily decrypt them.
- [x] 6. Pass share to new `submitRecoveryShare` RPC (after vote).
- [x] 6'. Re-construct `k_z` when sufficient shares (i.e. secret sharing threshold) have been submitted, decrypt ledger secrets from `ccf.shares` table and initiate private ledger recovery.
- [x] 6''. Support for multiple recoveries.
**[When all the steps above are implemented, this should be enough to have a functioning, yet incomplete, recovery scheme]**
- [x] 7. Generate ~_endorsed_~ network encryption key `nk` and pass it via the join protocol. The public key should be output by the starting node.
- [x] ~8. Members should encrypt their shares with `nk_pub` before passing it to their vote RPC. CCF should decrypt the encrypted share on proposal completion.~
- [ ] 9. Resilience to elections: submitted shares should be stored in the KV + end-to-end test for election during recovery (will be addressed in https://github.com/microsoft/CCF/issues/1051). 
- [x] 10. Issue new member shares on consortium update.
- [x] 11. Issue new member shares on re-keying (to be addressed in https://github.com/microsoft/CCF/issues/1049).
- [ ] 12. Remove sealing and update docs.
- [x] 13. ~Always re-key the ledger when issuing new shares.~ Re-key ledger when retiring active member.
- [x] 14. Threshold should be defined in a new configuration table and updatable via governance.

**Misc*

- [ ] `ServiceStatus` should use a state machine, in a similar way to `NodeState`.

**Comment by jumaffre** [comment]
The overall aim of this feature is to replace our current technique for recovery which relies on SGX data sealing. The issues with this approach are that 1) we need one surviving CPU when the network crashes (awkward in settings where nodes are spun dynamically on VMs) and 2) it is not resilient to elections between the time the recovery proposal is created and the time it is executed.

The current plan for the design of this feature, based on the TR and usability implications for CCF, is as follows:

- Each member `m` generates a new encryption private/public key pair `ksk_m` (the public half is recorded in the `ccf.members` table). 
- A new key `k_z` is generated in the enclave to encrypt the ledger secrets. `k_z` is then split into shares (using [sss](https://github.com/microsoft/CCF/pull/810)), one for each member and with a threshold `t` set by governance (i.e. you need `t` shares to reconstruct `k_z`).
- Each share is encrypted with `ksk_m`.
- A new _public_ table, `ccf.shares`, is added to CCF to keep track of the `k_z`-encrypted ledger secrets (this effectively replaces the existing sealed secrets file) and the `ksk_m`-encrypted members shares, i.e.:
```
ccf.shares (k -> v): z -> [ (ledger_secrets)k_z ; [(share_0)ksk_0; (share_1)ksk_1; ... ; (share_m)ksk_m; ] ]
```
- Every time new ledger secrets are created (e.g. on startup), a new entry in the `ccf.shares` table is added. Members can query CCF via a new `getEncryptedShare` RPC to retrieve their _encrypted_ share at any time (so they don't have to parse the ledger to find it).
- When it comes to recovering the service, each member votes for the recovery proposal, submitting its _decrypted_ share. Once `t` shares have been submitted, `k_z` is reconstructed, the ledger secrets  (lookup in `ccf.shares`)  are decrypted and the private recovery can start.

--  So far this is what the TR describes. --

However, we also need to take into account that members votes are stored in the `ccf.voting_history` _public_ table. It is then not possible to pass the _decrypted_ shares in the member vote RPC as these would then be recorded in plain text in the ledger. Instead, we could record the shares in a different RPC than the vote RPC and maintain the secret sharing context in memory of the primary node - but this is also not resilient to elections either.
Instead, the proposed solution is to create a new network encryption private/public key `nk`, different from the network identity `ni`, and passed between nodes during the join protocol. The public key `nk_pub` is output to the operator when the first node of a network starts up. `nk_pub` can then be distributed to the members who can encrypt their shares with `nk_pub` before attaching it to their votes. Once the proposal completes, the `nk_pub`-encrypted shares are read from the votes in the `ccf.proposals` table (*) and decrypted. This can be done on any node since the KV is replicated and `nk_priv` is accessible by all nodes.
The last issue is: how do members trust `nk_pub`? The proposed solution would be to endorse `nk_pub` with the network identity `ni` that can be trusted by the members, because of TLS.

(*) It is not yet clear whether it will be convenient to read the `nk_pub`-encrypted shares from `ccf.proposals` directly or create a new table for this. This is left as an implementation detail for now.

Other implications:
- A new `k_z` will have to be computed and shares re-distributed whenever the set of members changes (i.e. addition or deletion) and when the ledger is re-keyed.
- This approach pushes a fair bit of logic to the members who will have to 1) decrypt the share returned by `getEncryptedShare`, 2) encrypt it with `nk_pub`. In any case, we will have to make `scurl.sh` more intelligent to attach the `nk_pub`-encrypted share to the vote RPC.
- The secret sharing threashold `t` should not be greater than the quorum of members required to pass a proposal. 

Next: flesh-out a list of tasks to implement this feature.

**Comment by jumaffre** [comment]
Tasks identified so far (new/updated end-to-end tests not listed): see first ticket.

**Comment by jumaffre** [comment]
As further discussed offline today, further clarification:

- > The secret sharing threshold t should not be greater than the quorum of members required to pass a proposal.

Member key shares should not be passed with each vote. Instead, a new "launch_recovery" proposal should be staged by members when wanting to recover. Once the proposal is accepted (according to the governance `pass` script), members will be able to submit their shares to the public network (via a new `submitRecoveryShare`). It is only when the secret sharing threshold is reached that the recovery of the private ledger starts. This means than the threshold for secret sharing `t` can be totally different from the number of members required to pass a proposal.
Also note that the members who vote for the recovery can be totally different than the ones who submit their shares.

- Each new share shuffling (e.g. new member added or deleted) should also re-key the ledger. Otherwise, members with old shares could reconstruct the old `k_z` and retrieve the current ledger secrets.

- There is no need for a `ackShare` member RPC. If a service dies shortly after new shares have been issued, members can retrieve them from the recovered public-only service since encrypted shares are recorded in the KV in a public table.

**Comment by jumaffre** [comment]
More clarification:
- Since the members no longer pass their shares in the vote RPC, there is no need for the members to encrypt the shares with the network encryption public key. Instead, they can pass their (plaintext) shares via the `submitRecoveryShare` RPC over TLS. It is then up to the network to encrypt each share and record it in the KV (for resilience to election) using a symmetric key, i.e. in a public table but encrypted with the new ledger secrets.
- Each entry in the `ccf.shares` table should contain the ledger secrets since the beginning of time, encrypted with a new `k_z` so that the current set of members can recover a private ledger even after multiple re-keying, recoveries, etc.
