### ISSUE TITLE
Upgrade to OpenSSL 3.x

### ISSUE THREAD

**Issue by jumaffre** [microsoft/CCF#5291]
We should add support for OpenSSL 3.x before OpenSSL 1.1.1 [end of life](https://www.openssl.org/blog/blog/2023/03/28/1.1.1-EOL/). 

**Updated plan** (16/06/02023)
- OpenSSL 1.1.1 will be supported by Canonical on Ubuntu 20.04 until 20.04 EOL (May 2025) so CCF will remain on Ubuntu 20.04 and use the distribution OpenSSL 1.1.1 for the host on SGX, but also for SNP and Virtual enclaves. 
- Open Enclave will update to OpenSSL 3.x (see https://github.com/openenclave/openenclave/issues/4759), which we'll use for SGX enclaves. 
- We should therefore provide support for both OpenSSL 1.1.1 (host + SNP/Virtual) and 3.x (SGX) and be able to run CCF enclaves from both. 

```[tasklist]
### Tasks (see <https://github.com/microsoft/CCF/pull/5293> for pointers)
- [x] SHA256 (#5336): `SHA256_Init`, `SHA256_Update`, `SHA256_Final`
- [x] EC_KEY (#5481): `EC_KEY_new_by_curve_name`, `EC_KEY_free`, `EC_KEY_set_public_key_affine_coordinates`, `EC_KEY_get0_group`, `EC_KEY_set_public_key`, `EC_KEY_set_private_key`
- [x] EVP_PKEY (#5481): `EVP_PKEY_set1_EC_KEY`, `EVP_PKEY_get0_EC_KEY`, `EVP_PKEY_get0_RSA`, `EVP_PKEY_set1_RSA`, `EVP_PKEY_get1_EC_KEY`
- [x] RSA (#5481): `RSA_new`, `RSA_generate_key_ex`, `RSA_free`, `RSA_set0_key`, `RSA_set0_factors`, `RSA_set0_crt_params`, `RSA_get0_n`, ` RSA_get0_e`, `RSA_get0_d`, `RSA_get0_p`, `RSA_get0_q`, `RSA_get0_dmp1`, `RSA_get0_dmq1`, `RSA_get0_iqmp`
- [x] d2i (#5481): `d2i_RSA_PUBKEY`
- [ ] Engine (#5569): `ENGINE_load_rdrand`, `ENGINE_by_id`, `ENGINE_init`, `ENGINE_set_default`, `ENGINE_free`
- [x] Update (#5572) [`merklecpp`](https://github.com/microsoft/merklecpp), which makes use of `SHA256` API.
```

Some notes:
- `/opt/openenclave/lib/openenclave/host/liboehostverify.a` pulls `/usr/lib/x86_64-linux-gnu/libcrypto.so` (the installed OpenSSL crypto library). This is OK, but makes it hard to build a CCF enclave with a custom installation of OpenSSL. 
- ~As discussed with @achamayou, because the OpenSSL 3.x deb package is only available on Ubuntu 22.04, we can (and should!) upgrade the Virtual/SNP images to use Ubuntu 22.04. However, these platforms still require Open Enclave HostVerify, which is currently only tested with Ubuntu 20.04.~
