### ISSUE TITLE
PBFT to store meta data in the KV that will be in turn encrypted, serialized and persisted to the ledger

### ISSUE THREAD

**Issue by olgavrou** [microsoft/CCF#539]
**Overview**

Right now PBFT uses a `LedgerEnclave` object to write pre-prepares and requests to the ledger. These are not encrypted. We want PBFT to store this "meta data" in the KV and from there eventually persist to the ledger.

We want two types of KV maps. `derived` maps and `replicated` maps. We want to encrypt and serialize both, but we don't want to replicate the derived maps or persist them to the ledger.

In Raft all maps (at least for now) are considered replicated ones.

In the PBFT scenario where we have derived maps and replicated maps, we want to implement two Merkle trees. One over the replicated maps only and one over the entire state of the KV (replicated and derived maps). Both types of maps need to therefore be serialized and encrypted.

**Action points**

From the CCF side the steps that need to be taken are:

- [x] 1. Add a property (Boolean) to the KV `Map` that indicates if we want that map to replicated or not, defined on map creation based on the consensus protocol being built
- [x] 2. `Tx::serialise()` needs to return two vectors, one containing the derived maps write set encrypted and serialized and one containing the replicated maps write set encrypted and serialized
- [x] 3. Create the map where the pre-prepare and its request(s) will be stored into
- [x] 4. Create two merkle trees, one being updated due to the replicated maps and one being updated due to all of the maps

From the PBFT side of things the steps that need to be taken are:

- [x] 5. The flow of a request batch will need to change. 
   - a. A pre-prepare gatheres enough requests and is ready to execute them (call to `execute_tentative`
   - b. Every call to `process_pbft` will create a new transaction, write the request to the replicated request table, populate the derived tables by executing the request and then commit (and finally will trigger replicate)
  -  [x] c. This will update the two merkle trees and return to `Replica` the merkle tree roots (as is done now but for one merkle tree)
  - [x] d. When the requests are done, pre-prepare can be completed by having the two merkle roots written to it. 
  - e. Replica then calls `process_pbft` again with a "request" to store that pre-prepare in the replicated request table, which will in turn be written to the ledger
  - f. The pre-prepare can be broadcasted to the backups as usual

**Points of discussion**

Regarding what happens when `Consensus::replicate()` is called in the PBFT scenario.

Right now, PBFT uses its own channels to distribute requests and pre-prepares. Requests get sent via the client-proxy and pre-prepares (along with any other pbft-related message) via the Node's send() method.

We can either implement `Consensus::replicate()` to only persist the entries to the ledger and keep the rest of the PBFT communication as it is now.

OR

We can implement `Consensus::replicate()` to actually replicate the tables that hold the requests and the pre-prepares. This has the nice effect that the two consensuses behave in a similar way. But then we need to have client-proxy not send the requests (which is an easy thing to do) but we also need to tell PBFT to not send out the pre-prepares as they will be communicated via the table replication. This has the down side of creating two ways for PBFT replicas to communicate, one via the protocol (which they still need to do for the prepare, commit, response messages) and one via `replicate` for the requests and the pre-prepares. We could have all of the messages written to the KV and communicated via `replicate`, but then we will need to write everything to the KV tables and persist them to the ledger which I don't think is something that we want to do.

**Comment by achamayou** [comment]
I think I’d rather have a Boolean « replicated » attribute. There’s no clear case for a third state, and metadata is usually data about data, which isn’t really what we have here.

We will call replicate in both cases, but some tables will be replicated and some not, and that’s up to whoever creates the tables.

**Comment by olgavrou** [comment]
Proposed initial layout

![primary](https://user-images.githubusercontent.com/10447059/68596779-b022dd80-0493-11ea-9d3e-454bdee1751a.png)

![backup](https://user-images.githubusercontent.com/10447059/68596786-b4e79180-0493-11ea-8344-c0f837528de9.png)

<details><summary>Collapsible section</summary>
<p> `Primary`

.. mermaid::

    sequenceDiagram
        participant Client
        participant Frontend
        participant History
        participant KV
        participant Pbft
        participant Replica
        participant Ledger
        participant Backups

        Client->>Frontend: JSON-RPC Request
        Frontend->>History: add_request()


        History->>Pbft: on_request()
        Pbft->>Backups: Client Proxy broadcast request to backups
        Pbft->>Replica: recv_message()

        Replica->>Replica: store::TX
        Replica->>Replica: create pre-prepare
        Replica->>Replica: store::TX::get_view::put(pre-prepare and request(s))
        Replica->>Replica: exec_command(store::TX)
        Replica->>Frontend: process_pbft(store::TX)
        Frontend->>Frontend: process_json(store::TX)
        Frontend->>KV: commit()
        KV->>KV: serialise() to return 2 vectors (derived and all)
        KV->>History: on_result()
        History->>History: update merkle trees and update merkle_roots
        History->>KV: _
        KV->>Pbft: replicate(merkle_roots, serialized and encrypted data from replicated tables)
        Pbft->>Ledger: put_entry(merkle_roots, data from replicated tables)
        Pbft->>KV: _
        KV->>Frontend: _
        Frontend->>Pbft: return from process_pbft with merkle_roots populated
        Pbft->>Pbft: complete pre-prepare by setting merkle_root(s)
        Pbft->>Backups: broadcast pre-prepare



`Backup`

.. mermaid::

    sequenceDiagram
        participant Primary
        participant Frontend
        participant History
        participant KV
        participant Pbft
        participant Replica
        participant Ledger
        participant Backups

        Primary->>Pbft: send pre-prepare
        Pbft->>Replica: recv_message()

        Replica->>Replica: store::TX
        Replica->>Replica: store::TX::get_view::put(pre-prepare(without the MT root) and request(s))
        Replica->>Replica: exec_command(store::TX)
        Replica->>Frontend: process_pbft(store::TX)
        Frontend->>Frontend: process_json(store::TX)
        Frontend->>KV: commit()
        KV->>KV: serialise() to return 2 vectors (derived and all)
        KV->>History: on_result()
        History->>History: update merkle trees and update merkle_roots
        History->>KV: _
        KV->>Pbft: replicate(merkle_roots, serialized and encrypted data from replicated tables)
        Pbft->>Ledger: put_entry(merkle_roots, data from replicated tables)
        Pbft->>KV: _
        KV->>Frontend: _
        Frontend->>Pbft: return from process_pbft with merkle_roots populated
        Pbft->>Pbft: complete pre-prepare by setting merkle_root(s)
        Pbft->>Backups: broadcast pre-prepare </p>

**Comment by olgavrou** [comment]
After discussion with @ashamis updated ticket and diagrams

![primary](https://user-images.githubusercontent.com/10447059/68855207-b0122000-06d5-11ea-9c14-3282f2455d1a.png)

![backup](https://user-images.githubusercontent.com/10447059/68855223-b7d1c480-06d5-11ea-88ba-45763bbf0963.png)

<details><summary>Collapsible section</summary>
<p> `Primary`

.. mermaid::

    sequenceDiagram
        participant Client
        participant Frontend
        participant History
        participant KV
        participant Pbft
        participant Replica
        participant LedgerWriter
        participant Ledger
        participant Backups

        Client->>Frontend: JSON-RPC Request
        Frontend->>History: add_request()


        History->>Pbft: on_request()
        Pbft->>Backups: Client Proxy broadcast request to backups
        Pbft->>Replica: recv_message()

        Replica->>Replica: create pre-prepare
        Replica->>Replica: exec_command()
        Replica->>Frontend: process_pbft()
        Frontend->>Frontend: process_json()
        Frontend->>KV: commit()
        KV->>KV: serialise() to return 2 vectors (derived and all)
        KV->>History: on_result()
        History->>History: update merkle trees and update merkle_roots
        History->>KV: _
        KV->>Pbft: replicate(will be empty, only derived tables have been altered)

        Pbft->>KV: _
        KV->>Frontend: _
        Frontend->>Pbft: return from process_pbft
        Pbft->>Replica: return from exec_command
        Replica->>LedgerWriter: write
        LedgerWriter->>LedgerWriter: Store::Tx::put::requests to replicated-tables
        LedgerWriter->>LedgerWriter: Store::Tx::commit()
        LedgerWriter->>KV: serialise, update merkle trees and merkle_roots
        KV->>Pbft: replicate(replicated-tables populated with request(s) only)
        Pbft->>Ledger: put_entry(requests(s))
        LedgerWriter->>KV: get merkle roots
        LedgerWriter->>Replica: set merkle roots and complete pre-prepare
        Replica->>LedgerWriter: write
        LedgerWriter->>LedgerWriter: Store::Tx::put::pre-prepare with merkle_roots
        LedgerWriter->>LedgerWriter: Store::Tx::commit() [... continue as above]
        Replica->>Backups: broadcast pre-prepare

`Backup`

.. mermaid::

    sequenceDiagram
        participant Primary
        participant Frontend
        participant History
        participant KV
        participant Pbft
        participant Replica
        participant LedgerWriter
        participant Ledger

        Primary->>Pbft: send pre-prepare
        Pbft->>Replica: recv_message()

        Replica->>Replica: exec_command()
        Replica->>Frontend: process_pbft()
        Frontend->>Frontend: process_json()
        Frontend->>KV: commit()
        KV->>KV: serialise() to return 2 vectors (derived and all)
        KV->>History: on_result()
        History->>History: update merkle trees and update merkle_roots
        History->>KV: _
        KV->>Pbft: replicate(will be empty, only derived tables have been altered)

        Pbft->>KV: _
        KV->>Frontend: _
        Frontend->>Pbft: return from process_pbft
        Pbft->>Replica: return from exec_command
        Replica->>LedgerWriter: write
        LedgerWriter->>LedgerWriter: Store::Tx::put::requests to replicated-tables
        LedgerWriter->>LedgerWriter: Store::Tx::commit()
        LedgerWriter->>KV: serialise, update merkle trees and merkle_roots
        KV->>Pbft: replicate(replicated-tables populated with request(s) only)
        Pbft->>Ledger: put_entry(requests(s))
        LedgerWriter->>KV: get merkle roots
        LedgerWriter->>Replica: set merkle roots and complete pre-prepare
        Replica->>LedgerWriter: write
        LedgerWriter->>LedgerWriter: Store::Tx::put::pre-prepare with merkle_roots
        LedgerWriter->>LedgerWriter: Store::Tx::commit() [... continue as above] </p>

**Comment by achamayou** [comment]
@olgavrou calling replicate() on the replicas to get the write to ledger side-effect is functionally correct, but is surprising from a naming perspective.

**Comment by olgavrou** [comment]
@achamayou yes we can either rename replicate() to something like persist() and then each consensus protocol can do as it pleases. Or we can add another method to `Consensus` called persist() and call both replicate() and persist().

**Comment by olgavrou** [comment]
After discussion with @ashamis and @achamayou updated ticket description and diagrams

![primary](https://user-images.githubusercontent.com/10447059/68888004-fd13e780-0711-11ea-9c70-278e7f7ca5dc.png)

![backup](https://user-images.githubusercontent.com/10447059/68888017-043af580-0712-11ea-9050-e765514beff6.png)

<details><summary>Collapsible section</summary>
<p>
`Primary`

.. mermaid::

    sequenceDiagram
        participant Client
        participant Frontend
        participant History
        participant KV
        participant Pbft
        participant Replica
        participant Ledger
        participant Backups

        Client->>Frontend: JSON-RPC Request
        Frontend->>History: add_request()


        History->>Pbft: on_request()
        Pbft->>Backups: Client Proxy broadcast request to backups
        Pbft->>Replica: recv_message()

        Replica->>Replica: create pre-prepare
        loop for each request in pre-prepare
            Replica->>Replica: exec_command()
            Replica->>Frontend: process_pbft()
            Frontend->>Frontend: Tx::put::request in replicated-request-table
            Frontend->>Frontend: process_json()
            Frontend->>KV: commit()
            KV->>KV: serialise() to return 2 vectors (derived and replicated)
            KV->>History: on_result()
            History->>History: update merkle trees and update merkle_roots
            History->>KV: _
            KV->>Pbft: replicate([replicated and derived write sets])
            Pbft->>Ledger: put_entry()

            Pbft->>KV: _
            KV->>Frontend: _
            Frontend->>Pbft: return from process_pbft
            Pbft->>Replica: return from exec_command with fresh merkle_roots
        end
        
        Replica->>Replica: set merkle roots and complete pre-prepare
        Replica->>Replica: call exec_command with "request" to store the pre-prepare to the replicated-request-table
        Replica->>Backups: broadcast pre-prepare

`Backup`

.. mermaid::

    sequenceDiagram
        participant Primary
        participant Frontend
        participant History
        participant KV
        participant Pbft
        participant Replica

        Primary->>Pbft: send pre-prepare
        Pbft->>Replica: recv_message()

        loop for each request in pre-prepare
            Replica->>Replica: exec_command()
            Replica->>Frontend: process_pbft()
            Frontend->>Frontend: Tx::put::request in replicated-request-table
            Frontend->>Frontend: process_json()
            Frontend->>KV: commit()
            KV->>KV: serialise() to return 2 vectors (derived and replicated)
            KV->>History: on_result()
            History->>History: update merkle trees and update merkle_roots
            History->>KV: _
            KV->>Pbft: replicate([replicated and derived write sets]])
            Pbft->>Ledger: put_entry()

            Pbft->>KV: _
            KV->>Frontend: _
            Frontend->>Pbft: return from process_pbft
            Pbft->>Replica: return from exec_command with fresh merkle_roots
        end

        Replica->>Replica: check that the local merkle roots match with the pre-prepare roots
        Replica->>Replica: call exec_command with "request" to store the pre-prepare to the replicated-request-table
        Replica->>Backups: broadcast prepare
        Replica->>Primary: broadcast prepare
</p>

**Comment by olgavrou** [comment]
In taking steps to implement the two merkle trees (one for replicated one for all data) we need to also be able to distinguish between the two types of write sets when we are deserializing a write set that has been replicated (raft) or is being replayed (pbft).

`Store::deserialise()` deserializes all of the data together without distinguishing between replicated and derived, since when we write the data to the ledger we write the replicated data concatenated with the derived data.

I am looking into having the `GenericDeserialiseWrapper` return the size of the data it has deserialized (we deserialize per map in `Store`) and if the map we are deserializing is a replicated one, then we copy that data (the encrypted/serialised data that has been replicated/replayed) into a vector. So in the end we have two vectors one with all of the data and one with only the replicated data and we can update the two merkle trees accordingly.

I have started to play around with this but please let me know if I am missing something or if anyone thinks there is a better solution to this.

**Comment by olgavrou** [comment]
Distinguishing derived and replicated on deserialization will happen via the use of flatbuffers (added [here](https://github.com/microsoft/CCF/pull/579))
