### ISSUE TITLE
JwtAuthnPolicy could validate the key_issuer against iss

### ISSUE THREAD

**Issue by achamayou** [microsoft/CCF#5809]
`JwtAuthnPolicy` currently exposes an authenticated `key_issuer`, and an un-checked `iss` field from the token. It is up to the application code to check that they match (which should be the case when the standard is followed), and to include logic used to implement [multi-tenant support for example](https://learn.microsoft.com/en-us/entra/identity-platform/access-tokens#validate-the-issuer), when applicable.

We could improve on this by:

1. Checking `key_issuer` == `iss`
2. If not, instantiate the `key_issuer` using the AAD-specific logic described in the link above and the `tid`

This would break neither standards-compliant, nor AAD use cases, and would reduce the risk of incorrect token validation by the application code.
```[tasklist]
### Tasks
- [x] Do the issuer validation against the token
- [x] Migration: check how the old code works with new nodes in the network and prepare a PR to 4.x if needed
- [x] Migration: make sure we get rid of the old table with time
```

**Comment by eddyashton** [comment]
@maxtropets

**Comment by maxtropets** [comment]
**Key points**

- We improve token authorization by adding checks against `issuer` data for both key and token.
- In the scope of this ticket we assume we can’t have more than one unique `kid`. The documentation [doesn’t mention](https://learn.microsoft.com/en-us/entra/identity-platform/access-tokens) what should we do if doesn’t come true. It is up to https://github.com/microsoft/CCF/issues/5177 to either:
  - prove the point, or
  - prove that wrong, but not an issue, or
  - prove that wrong and to be an issue
    - come up with the fix in this case
- **Fixups we consider**
  - Check `token.iss` and `key.issuer` match (caveats for multi-tenancy mode, see below)
  - `token.iss`’s tenant-id and `token.tid` claim match
  - key.issuer matches the expected issuer when fetching
    - To be discussed further
    - Doc [says](https://learn.microsoft.com/en-us/entra/identity-platform/access-tokens#recap)
      - Identify key in the metadata based on the kid header. **Check the "issuer" property attached to the key in the metadata document**
```
      // ...
      if (configuration.allowedIssuer != "*"
          && configuration.allowedIssuer != issuer)
          throw validationException;
      // ...
```              
- The algorithm to be implemented is nicely summarized [in the documentation](https://learn.microsoft.com/en-us/entra/identity-platform/access-tokens#recap)
- Multi-tenancy VS single-tenancy
  - First we should check for single/muti-tenancy: `key.issuer` = `prefix/{tenant-id}/suffix` stands for multi-tenancy and everything else means single-tenancy. We will choose the mode by `{tenant_id}` presence (curly braces included).
  - Now, for single-tenancy, `token.iss` has to match `key.issuer`
  - For multi-tenancy
    - Replace `{tenant-id}` with `token.tid` , so consider `issuer*` = `prefix/token.tid/suffix`
    - Now, `token.iss` has to match `issuer*`

**Comment by maxtropets** [comment]
After implementing the above, I've faced a complication.

Currently, we have only one tables in the KV to map the kid to issuer. The problem is, that for MSFT Entra multitenancy mode, we have to compare the token.iss claim against the "issuer" specified in the **key**.

As soon as the multitenant endpoint can (and probably will) provide multiple keys with **different issuers**, I first decided to overwrite the original issue in the kid->issuer table and this worked well.

However, as I revealed in tests, this breaks down `remove_jwt_keys.`, because we lose the original issuer, and now we can't find out which keys to remove for any particular issuer anymore.

The only way to fix it I came up with is change the schema (extend kid->issuer or add new table). Needs to be discussed further.

**Comment by achamayou** [comment]
@maxtropets I think what this effectively means is that fixing #5177 first is necessary. Let's discuss this with @eddyashton.

**Comment by maxtropets** [comment]
Regarding the first one - it seems they carry the same public key [common Entra endpoint](https://login.microsoftonline.com/common/v2.0/.well-known/openid-configuration).

The first non-common tenant in the [keys](https://[login.microsoftonline.com/common/discovery/v2.0/keys](https://login.microsoftonline.com/common/discovery/v2.0/keys)) is `9188040d-6c67-4c5b-b112-36a304b66dad` with `kid=SP89B0VYWSffbnOcvhkYBmPdo3M` exposes it's own OpenID keys at [https://[login.microsoftonline.com/9188040d-6c67-4c5b-b112-36a304b66dad/v2.0/.well-known/openid-configuration](https://login.microsoftonline.com/9188040d-6c67-4c5b-b112-36a304b66dad/v2.0/.well-known/openid-configuration)

If we go to the keys in there, we can find the `kid=SP89B0VYWSffbnOcvhkYBmPdo3M` 

Both keys with `kid=SP89B0VYWSffbnOcvhkYBmPdo3M`, from the common endpoint and specified endpoint, carry the same public key. However we don't have see anything said that this's an expected behaviour, and I don't really see how we can deal with that.

**Comment by maxtropets** [comment]
Regarding the second point about different issuer constraints.

It seems it's not true for the keys published right now, because the keys they point to, which are
* [https://login.microsoftonline.com/common/discovery/v2.0/keys](https://login.microsoftonline.com/common/discovery/v2.0/keys)
* and [https://login.microsoftonline.com/9188040d-6c67-4c5b-b112-36a304b66dad/discovery/v2.0/keys](https://login.microsoftonline.com/9188040d-6c67-4c5b-b112-36a304b66dad/discovery/v2.0/keys)

seem to an alias of the same document - **the contents are identical**.

However we also don't have anything saying it's guaranteed to not happen.

**Comment by maxtropets** [comment]
Added #6204 to implement domain check on fetch

**Comment by maxtropets** [comment]
Decided to complete follow-up tickets in this PR to avoid scattering between releases

**Comment by maxtropets** [comment]
Done in https://github.com/microsoft/CCF/pull/6175
