### ISSUE TITLE
CCF consensus verification roadmap

### ISSUE THREAD

**Issue by achamayou** [microsoft/CCF#5822]
This issue aims to create a priority-ordered list of items that need to be tackled to complete the verification of CCF Raft, and summarise their dependencies so they can be picked up efficiently.

- [x] `ccfraft.tla` startup is incorrect, and needs to be aligned with the implementation. This our top priority item, it's documented at length in #5220, #5749, and there's an ongoing effort in #5769 to fix it. We should not be adding any more invariants, properties etc until this has been addressed.
- [x] `ccfraft.tla` commit is incorrect, and needs to be aligned with the implementation. This is documented in #5798. This does not depend on the first item, and can be picked up independently.
- [x] Check, and eliminate `NotifiyCommit` messages, documented in #5280. Those do not exist in the implementation, will not trace validate.
- [x] Split `leadership_state` from `membership_state`. #5902 They are confused in the spec (`RetiredLeader`). Prerequisite to:
- [x] Complete retirement modeling, see #4818.

#2577, #5678 and #5290 are lower priority than all of the above, and some of them may reconsidered altogether once these are complete.

**Comment by achamayou** [comment]
This roadmap has run its course, we can look at the next steps in the larger-scoped #5057.
