### ISSUE TITLE
Extend Merkle tree signature list

### ISSUE THREAD

**Issue by maxtropets** [microsoft/CCF#6441]
Ultimate goal: **support COSE (and probably more) signatures** for Merkle's root.

Bullet points
- reverse-compatibility
  - old tooling should work with raw signatures/receipts signed by the new code
- storing signatures
- tooling: support multi signature verification

```[tasklist]
### Tasks
- [ ] https://github.com/microsoft/CCF/issues/6445
- [ ] https://github.com/microsoft/CCF/issues/6449
- [ ] https://github.com/microsoft/CCF/issues/6462
- [ ] https://github.com/microsoft/CCF/issues/6477
```

**Comment by achamayou** [comment]
@maxtropets as spotted by the LTS test, and as discussed, there is one more item here: backport a change to 5.x that allows nodes to accept (and verify) COSE signatures, without emitting them when they are primary. This will enable the usual three phase upgrade (which is just two phases in this case, since we have no immediate plan to stop emitting the old signatures).
